# AudioMuse-AI Deployment Configuration
#
# WORKER TEMPLATE - Run this for heavy CPU tasks like analysis and clustering, connected to a lightweight server with Jellyfin and AudioMuse-AI Flask application and databases.
version: '3.8'
services:
  # AudioMuse-AI Worker service (GPU-dependent)
  audiomuse-ai-worker:
    # optionally choose between the ARM/Intel image audiomuse-ai:latest and the experimental nvidia image audiomuse-ai:latest-nvidia
    image: ghcr.io/neptunehub/audiomuse-ai:latest # audiomuse-ai:latest-nvidia
    container_name: audiomuse-ai-worker-instance
    ports:
      - "8029:8000"  # Expose worker API
    environment:
      SERVICE_TYPE: "worker"
      # Jellyfin specific settings (comment these with # if you are using Emby, Navidrome, or Lyrion)
      MEDIASERVER_TYPE: "jellyfin" # Specify the media server type
      JELLYFIN_USER_ID: "${JELLYFIN_USER_ID}"
      JELLYFIN_TOKEN: "${JELLYFIN_TOKEN}"
      JELLYFIN_URL: "${JELLYFIN_URL}"
      # EMBY specific settings (uncomment these if you are using Emby) #
      #MEDIASERVER_TYPE: "emby" # Specify the media server type
      #EMBY_USER_ID: "${EMBY_USER_ID}"
      #EMBY_TOKEN: "${EMBY_TOKEN}"
      #EMBY_URL: "${EMBY_URL}"
      # LYRION specific settings (uncomment these if you are using Lyrion) #
      #MEDIASERVER_TYPE: "lyrion"
      #LYRION_URL: "${LYRION_URL}"
      # NAVIDROME specific settings (uncomment these if you are using Navidrom) #
      #MEDIASERVER_TYPE: "navidrome"
      #NAVIDROME_URL: "${NAVIDROME_URL}"
      #NAVIDROME_USER: "${NAVIDROME_USER}"
      #NAVIDROME_PASSWORD: "${NAVIDROME_PASSWORD}"
      POSTGRES_USER: ${POSTGRES_USER:-audiomuse}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-audiomusepassword}
      POSTGRES_DB: ${POSTGRES_DB:-audiomusedb}
      POSTGRES_HOST: "${WORKER_POSTGRES_HOST:-postgres}" # Replace via WORKER_POSTGRES_HOST in .env when running remotely
      POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
      REDIS_URL: "${WORKER_REDIS_URL:-redis://redis:6379/0}"  # Set WORKER_REDIS_URL in .env for remote connections
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
      MISTRAL_API_KEY: "${MISTRAL_API_KEY}"
      OLLAMA_SERVER_URL: "${OLLAMA_SERVER_URL}"
      TEMP_DIR: "/app/temp_audio"
      # uncomment below if you want to use the experimental nvidia image
      #NVIDIA_VISIBLE_DEVICES: "0"
      #NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
      # Remote worker Variables [Not Required for the All-In-One Solution / Basic Setup]
      # Tells the Worker/Flask App how the Postgres Host is reachable
      WORKER_POSTGRES_HOST: "${WORKER_POSTGRES_HOST}"
      # Tells the Worker/Flask App how the Redis Service is reachable
      WORKER_REDIS_URL: "${WORKER_REDIS_URL}"
    volumes:
      - temp-audio-worker:/app/temp_audio
    restart: unless-stopped
    # uncomment below if you want to use the experimental nvidia image
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          device_ids: [ "0" ]
    #          capabilities: [ gpu ]

volumes:
  temp-audio-worker:
